language: d
sudo: false

d:
  - dmd
  - ldc
  - gdc

env:
  - CONFIG=unittest
  - CONFIG=unittest-vibed

matrix:
  allow_failures:
  - d: gdc
    env: CONFIG=unittest-vibed

install:
  - $DC | head -3

script:
  - export PATH=$PATH:~/bin/
  - dub --build=unittest --config=$CONFIG --compiler=$DC -v
